name: Project

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install FPGA dependencies
        run: sudo apt-get install -y arachne-pnr fpga-icestorm yosys

      - name: Build the targer
        run: make build